# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: News-Website_development

test:
  <<: *default
  database: News-Website_test


production:
  <<: *default
  database: News-Website_production
  username: kioshi
  password: <%= ENV['NEWS-WEBSITE_DATABASE_PASSWORD'] %>
